In [1]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [9]:
path ='DOB_Complaints.csv'
complaints_df =pd.read_csv(path)

C:\Users\Alyasi\AppData\Local\Temp\ipykernel_29960\1325977586.py:2: DtypeWarning: Columns (5,7,8,9) have mixed types. Specify dtype option on import or set low_memory=False.
  complaints_df =pd.read_csv(path)

In [7]:
display(complaints)

,Complaint Number,Status,Date Entered,House Number,House Street,ZIP Code,BIN,Community Board,Special District,Complaint Category,Unit,Disposition Date,Disposition Code,Inspection Date,DOBRunDate
0,1000008,CLOSED,01/03/1989,101,1 AVENUE,10003,1006289,103,NaN,3,MAN.,01/04/1989,I2,01/03/1989,2024-10-21
1,1000009,CLOSED,01/03/1989,101,1 AVENUE,10003,1006289,103,NaN,1,MAN.,01/04/1989,I2,01/04/1989,2024-10-21
2,4000001,CLOSED,01/03/1989,255-17,IOWA ROAD,11362,4171655,411,NaN,45,QNS.,02/21/1996,C2,03/27/1989,2024-10-21
3,1000017,CLOSED,01/03/1989,179,WEST BROADWAY,10013,1001966,101,NaN,31,MAN.,01/06/1989,I2,01/04/1989,2024-10-21
4,1000022,CLOSED,01/03/1989,133,EAST 22 STREET,10010,1086544,106,NaN,46,MAN.,01/06/1989,A1,01/04/1989,2024-10-21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2900477,3856352,CLOSED,05/27/2022,196,BROADWAY,11211,3059545,301,NaN,73,BKLYN,05/27/2022,A8,05/27/2022,2024-10-21
2900478,3862142,CLOSED,07/05/2022,1165,ELTON STREET,11239,3398621,305,NaN,53,BKLYN,07/13/2022,I2,07/13/2022,2024-10-21
2900479,3871303,CLOSED,08/30/2022,21,FULLER PLACE,11215,3027309,307,NaN,45,Q-L,01/06/2023,C2,01/06/2023,2024-10-21
2900480,4905111,CLOSED,10/18/2022,60-28,80 AVENUE,11385,4436554,405,NaN,7J,RTEU,10/19/2022,C2,10/19/2022,2024-10-21
2900481,3879796,CLOSED,10/28/2022,1753,65 STREET,11204,3133514,311,NaN,49,SPOPS,12/14/2022,A8,12/13/2022,2024-10-21

In [10]:
complaints_df.Status

0          CLOSED
1          CLOSED
2          CLOSED
3          CLOSED
4          CLOSED
            ...
2900477    CLOSED
2900478    CLOSED
2900479    CLOSED
2900480    CLOSED
2900481    CLOSED
Name: Status, Length: 2900482, dtype: object

In [12]:
# make dictonary
complaints.Status.value_counts()

Status
CLOSED    2874315
ACTIVE      26167
Name: count, dtype: int64

In [13]:
# subsection of data frame 
# active complaint
active_complaints_df = complaints_df[[complaint for complaint in complaints_df.Status == 'ACTIVE']]

In [14]:
display(active_complaints_df)

,Complaint Number,Status,Date Entered,House Number,House Street,ZIP Code,BIN,Community Board,Special District,Complaint Category,Unit,Disposition Date,Disposition Code,Inspection Date,DOBRunDate
305840,4164903,ACTIVE,04/22/2003,37-06,82 STREET,11372.0,4545554,403.0,NaN,49,NaN,NaN,NaN,NaN,2024-10-21
314614,1110389,ACTIVE,07/31/2003,1313,ST NICHOLAS AVENUE,10033.0,1063555,112.0,NaN,49,NaN,NaN,NaN,NaN,2024-10-21
314661,5040821,ACTIVE,09/06/2003,330,FINGERBOARD ROAD,10305.0,5045459,502.0,NaN,49,NaN,NaN,NaN,NaN,2024-10-21
333897,4173348,ACTIVE,08/22/2003,2304,36 AVENUE,11106.0,4004237,401.0,NaN,49,NaN,NaN,NaN,NaN,2024-10-21
337375,3117206,ACTIVE,08/11/2003,45,GARNET STREET,11231.0,3008170,306.0,NaN,49,NaN,NaN,NaN,NaN,2024-10-21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2900432,3965417,ACTIVE,06/19/2024,1165,ELTON STREET,11239,3398621,305,NaN,6M,ELEVR,NaN,NaN,NaN,2024-10-21
2900434,4966349,ACTIVE,07/20/2024,60-28,80 AVENUE,11385,4436554,405,NaN,45,Q-L,09/12/2024,C3,09/12/2024,2024-10-21
2900435,3971680,ACTIVE,08/07/2024,1165,ELTON STREET,11239,3398621,305,NaN,6M,ELEVR,NaN,NaN,NaN,2024-10-21
2900441,2400076,ACTIVE,09/06/2024,500,EAST 166 STREET,10456,2001268,203,NaN,29,BRONX,09/27/2024,D1,09/27/2024,2024-10-21
2900444,4972355,ACTIVE,09/16/2024,60-28,80 AVENUE,11385,4436554,405,NaN,45,Q-L,NaN,NaN,NaN,2024-10-21

In [15]:
active_complaints_df[100:150]

,Complaint Number,Status,Date Entered,House Number,House Street,ZIP Code,BIN,Community Board,Special District,Complaint Category,Unit,Disposition Date,Disposition Code,Inspection Date,DOBRunDate
840976,1139915,ACTIVE,04/09/2005,208,EAST 82 STREET,10028.0,1048578,108.0,NaN,49,NaN,NaN,NaN,NaN,2024-10-21
850592,1140080,ACTIVE,04/12/2005,210,3 AVENUE,10003.0,1017882,106.0,NaN,49,NaN,NaN,NaN,NaN,2024-10-21
853351,1123667,ACTIVE,06/03/2004,217,EAST 85 STREET,10028.0,1085217,108.0,NaN,49,NaN,NaN,NaN,NaN,2024-10-21
863250,1260937,ACTIVE,07/17/2009,37,CROSBY STREET,10013.0,1076935,102.0,NaN,2F,ERT,07/30/2009,R8,07/30/2009,2024-10-21
863546,3313952,ACTIVE,07/31/2009,48,NORTH 1 STREET,11211.0,3335757,301.0,NaN,2F,ERT,07/31/2009,RN,07/31/2009,2024-10-21
863664,3312421,ACTIVE,07/18/2009,722,METROPOLITAN AVENUE,11211.0,3338159,301.0,NaN,2F,ERT,07/31/2009,R8,07/30/2009,2024-10-21
863673,3314006,ACTIVE,07/31/2009,55,HEYWARD STREET,11211.0,3060964,301.0,NaN,2F,ERT,07/31/2009,RA,07/31/2009,2024-10-21
863675,3314004,ACTIVE,07/31/2009,53,LYNCH STREET,11206.0,3061137,301.0,NaN,2F,ERT,05/22/2012,R8,04/02/2010,2024-10-21
863681,3314010,ACTIVE,07/31/2009,572,GRAND STREET,11211.0,3069511,301.0,NaN,2F,ERT,07/31/2009,RA,07/31/2009,2024-10-21
863682,3314011,ACTIVE,07/31/2009,572,GRAND STREET,11211.0,3069511,301.0,NaN,2F,ERT,07/31/2009,RM,07/31/2009,2024-10-21
863683,3314012,ACTIVE,07/31/2009,572,GRAND STREET,11211.0,3069511,301.0,NaN,2F,ERT,07/31/2009,RH,07/31/2009,2024-10-21
865077,3154881,ACTIVE,04/17/2005,986,EAST 58 STREET,11234.0,3350500,318.0,NaN,49,NaN,NaN,NaN,NaN,2024-10-21
866158,1140521,ACTIVE,04/19/2005,9,AVENUE B,10009.0,1004567,103.0,NaN,49,NaN,NaN,NaN,NaN,2024-10-21
867678,1262366,ACTIVE,08/04/2009,700,BROADWAY,10003.0,1008789,102.0,NaN,2F,ERT,08/04/2009,R8,08/04/2009,2024-10-21
869026,1124267,ACTIVE,06/14/2004,14,WEST 71 STREET,10023.0,1028597,107.0,NaN,49,NaN,NaN,NaN,NaN,2024-10-21
876962,3315011,ACTIVE,08/10/2009,405,SOUTH 3 STREET,11211.0,3414014,301.0,NaN,2F,FEU,04/06/2010,RM,04/03/2010,2024-10-21
891567,1141037,ACTIVE,04/26/2005,28,BOND STREET,10012.0,1008497,102.0,NaN,49,NaN,NaN,NaN,NaN,2024-10-21
895084,1141051,ACTIVE,04/27/2005,58,WEST 38 STREET,10018.0,1015983,105.0,NaN,49,NaN,NaN,NaN,NaN,2024-10-21
896716,1141240,ACTIVE,04/29/2005,33,GREENWICH STREET,10004.0,1000045,101.0,NaN,49,NaN,NaN,NaN,NaN,2024-10-21
908565,1141556,ACTIVE,05/04/2005,601,2 AVENUE,10016.0,1020093,106.0,NaN,49,NaN,NaN,NaN,NaN,2024-10-21
913205,1141622,ACTIVE,05/05/2005,358,WEST 44 STREET,10036.0,1024978,104.0,SCD,49,NaN,NaN,NaN,NaN,2024-10-21
917118,1125732,ACTIVE,07/12/2004,128,EAST 84 STREET,10028.0,1047661,108.0,NaN,49,NaN,NaN,NaN,NaN,2024-10-21
917696,3156937,ACTIVE,05/10/2005,8717,21 AVENUE,11214.0,3167951,311.0,NaN,49,NaN,NaN,NaN,NaN,2024-10-21
926361,1126065,ACTIVE,07/17/2004,4846,BROADWAY,10034.0,1081916,112.0,NaN,49,NaN,NaN,NaN,NaN,2024-10-21
927106,1126169,ACTIVE,07/20/2004,205,WEST 80 STREET,10024.0,1032662,107.0,NaN,49,NaN,NaN,NaN,NaN,2024-10-21
928396,2070294,ACTIVE,05/16/2005,530,WEST 236 STREET,10463.0,2084147,208.0,NaN,49,NaN,NaN,NaN,NaN,2024-10-21
935700,5046158,ACTIVE,07/25/2004,95,LABAU AVENUE,10301.0,5016809,501.0,NaN,49,NaN,NaN,NaN,NaN,2024-10-21
940377,3137429,ACTIVE,07/30/2004,4905,AVENUE D,11203.0,3327625,317.0,NaN,49,NaN,NaN,NaN,NaN,2024-10-21
943110,1145515,ACTIVE,07/02/2005,675,9 AVENUE,10036.0,1082497,104.0,SCD,49,NaN,NaN,NaN,NaN,2024-10-21
943733,1126872,ACTIVE,08/03/2004,1637,PARK AVENUE,10029.0,1052275,111.0,NaN,49,NaN,NaN,NaN,NaN,2024-10-21
948417,1127131,ACTIVE,08/08/2004,55,EXCHANGE PLACE,10004.0,1078988,101.0,NaN,49,NaN,NaN,NaN,NaN,2024-10-21
953825,1127252,ACTIVE,08/10/2004,83,WEST 125 STREET,10027.0,1053494,110.0,NaN,49,NaN,NaN,NaN,NaN,2024-10-21
958651,1127519,ACTIVE,08/16/2004,156,EAST 116 STREET,10029.0,1052280,111.0,NaN,49,NaN,NaN,NaN,NaN,2024-10-21
981840,3139587,ACTIVE,08/30/2004,814,CONEY ISLAND AVENUE,11218.0,3126911,312.0,NaN,49,NaN,NaN,NaN,NaN,2024-10-21
984146,1266245,ACTIVE,09/25/2009,477,BROOME STREET,10013.0,1007077,102.0,NaN,2F,FEU,09/29/2009,RA,09/23/2009,2024-10-21
987586,1266246,ACTIVE,09/25/2009,473,BROOME STREET,10013.0,1084911,102.0,NaN,2F,FEU,09/29/2009,RA,09/23/2009,2024-10-21
989393,3165015,ACTIVE,08/02/2005,2130,85 STREET,11214.0,3165885,311.0,NaN,49,NaN,NaN,NaN,NaN,2024-10-21
989473,3165022,ACTIVE,08/02/2005,2130,85 STREET,11214.0,3165885,311.0,NaN,49,NaN,NaN,NaN,NaN,2024-10-21
995663,3312407,ACTIVE,07/18/2009,629,UNION STREET,11215.0,3007214,306.0,NaN,2F,ERT,03/31/2010,R8,03/29/2010,2024-10-21
999992,1128600,ACTIVE,09/08/2004,191,ORCHARD STREET,10002.0,1005549,103.0,NaN,49,NaN,NaN,NaN,NaN,2024-10-21
1010878,1148274,ACTIVE,08/12/2005,88,EAST END AVENUE,10028.0,1085954,108.0,NaN,49,NaN,NaN,NaN,NaN,2024-10-21
1032452,1149214,ACTIVE,08/26/2005,317,EAST 75 STREET,10021.0,1045139,108.0,NaN,49,NaN,NaN,NaN,NaN,2024-10-21
1050808,3169418,ACTIVE,09/13/2005,504,74 STREET,11209.0,3148361,310.0,NaN,49,NaN,NaN,NaN,NaN,2024-10-21
1053874,1260955,ACTIVE,07/18/2009,16,BARROW STREET,10014.0,1010189,102.0,NaN,2F,ERT,10/26/2009,R8,10/22/2009,2024-10-21
1053876,1260952,ACTIVE,07/18/2009,18,MORTON STREET,10014.0,1009929,102.0,NaN,2F,ERT,10/26/2009,R8,10/22/2009,2024-10-21
1053877,1260956,ACTIVE,07/18/2009,31,RENWICK STREET,10013.0,1010299,102.0,NaN,2F,ERT,10/26/2009,R8,10/26/2009,2024-10-21
1053886,1260935,ACTIVE,07/17/2009,365,CANAL STREET,10013.0,1002957,102.0,NaN,2F,ERT,10/26/2009,R8,10/26/2009,2024-10-21
1053887,1260959,ACTIVE,07/18/2009,372,WEST 11 STREET,10014.0,1012004,102.0,NaN,2F,ERT,10/26/2009,R8,10/26/2009,2024-10-21
1073790,3335645,ACTIVE,03/16/2010,623,AVENUE U,11223.0,3192043,315.0,NaN,1G,STALL,01/16/2019,S7,01/16/2019,2024-10-21
1132845,1132980,ACTIVE,12/01/2004,1489,1 AVENUE,10021.0,1091832,108.0,NaN,49,NaN,NaN,NaN,NaN,2024-10-21